### ISSUE TITLE
[DB] Empty the Database

### ISSUE THREAD

**Issue by rlalleme** [Greg8978/toaster#10]
It would be nice to have the possibility to empty the database, all at once.

Basic use case:
With a script we add a set of facts
Some are changed
A new state must be created
The database is emptied and new facts are added (with a script again)

Would be better than to have to call "remove_fact" for all the facts.

It should keep the tables (obviously not their content) since the tables are established, from an XML file, when the database server is started.

**Comment by Greg8978** [comment]
It could be interested to have a request to empty a specific table and an other one for the whole database

**Comment by rlalleme** [comment]
So maybe the following service:
- /database/empty_database
- /database/empty_database_for_agent
- /database/reset_tables

The last one would remove all the entries in the tables, then delete the table, then create the new table either from the file database/id_list.xml or from the file given as argument of the reset_tables.

**Comment by sdevin** [comment]
In the pull request:
-  /database/empty_database
-  /database/empty_database_for_agent

**Comment by Greg8978** [comment]
Is this issue still open?

**Comment by shipra25jain** [comment]
There is a provision to empty the tables and database in execute_db service, then why this issue is still open?

**Comment by Greg8978** [comment]
Because the last one is not implemented:
/database/reset_tables
See rlalleme comment for details

**Comment by shipra25jain** [comment]
Okay. I will try to add the last one.
