### ISSUE TITLE
The field "valueType" is not set/sent

### ISSUE THREAD

**Issue by rlalleme** [Greg8978/toaster#11]
When a fact is added, the value from valueType is not kept OR if it is kept when the facts are requested it is not sent.

It is not possible to know the origin of the problem since /database/print service outputs:

> [ INFO] [1453220593.272033456]: subject_id = Location1
> [ INFO] [1453220593.272096972]: predicate = occupied
> [ INFO] [1453220593.272152165]: target_id = 
> [ INFO] [1453220593.272204989]: valueType = 
> [ INFO] [1453220593.272259194]: valueString = 
> [ INFO] [1453220593.272316653]: valueDouble = 1.0
> [ INFO] [1453220593.272369809]: observability = 0
> [ INFO] [1453220593.272425084]: confidence = 1
> [ INFO] [1453220593.272474344]: start = 0
> [ INFO] [1453220593.272523587]: end = 0

It shows that the valueDouble is set as expected but nothing is printed for the "valueType" field.

It is necessary to fix this issue since it is used to specify whether the receiver must read the valueString OR valueDouble field.

**Comment by sdevin** [comment]
Fixed (valueType was previously filled with valueString value):

fact_table_PR2_ROBOT
[ INFO] [1453284732.748610860]: ---
[ INFO] [1453284732.748624001]: subject_id = toto
[ INFO] [1453284732.748632719]: predicate = isOn
[ INFO] [1453284732.748641207]: propertyType = 
[ INFO] [1453284732.748648504]: target_id = tata
[ INFO] [1453284732.748656492]: valueType = 1
[ INFO] [1453284732.748663669]: valueString = tata
[ INFO] [1453284732.748671664]: valueDouble = 0.1
[ INFO] [1453284732.748678953]: observability = 0
[ INFO] [1453284732.748686677]: confidence = 0
[ INFO] [1453284732.748693270]: start = 0
[ INFO] [1453284732.748700995]: end = 0
