### ISSUE TITLE
[genom] compile failed because of database

### ISSUE THREAD

**Issue by Greg8978** [Greg8978/toaster#15]
function readDB changed signature.
It needs to be updated properly

**Comment by aclodic** [comment]
[ 97%] Building CXX object toaster/database_manager/CMakeFiles/run_server.dir/src/run_server.cpp.o
/home/aclodic/catkin_hydro/src/toaster/database_manager/src/run_server.cpp: In function 'int main(int, char*_)':
/home/aclodic/catkin_hydro/src/toaster/database_manager/src/run_server.cpp:2441:19: error: no matching function for call to 'run_server::readDb()'
/home/aclodic/catkin_hydro/src/toaster/database_manager/src/run_server.cpp:2441:19: note: candidate is:
/home/aclodic/catkin_hydro/src/toaster/database_manager/src/run_server.cpp:704:10: note: void run_server::readDb(toaster_msgs::Empty::Request&, toaster_msgs::Empty::Response&)
/home/aclodic/catkin_hydro/src/toaster/database_manager/src/run_server.cpp:704:10: note:   candidate expects 2 arguments, 0 provided
make[2]: *_\* [toaster/database_manager/CMakeFiles/run_server.dir/src/run_server.cpp.o] Error 1
make[1]: **\* [toaster/database_manager/CMakeFiles/run_server.dir/all] Error 2
make: **\* [all] Error 2
make: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!

**Comment by Greg8978** [comment]
Updated the database with last pull request
