### ISSUE TITLE
[pdg] object place after remove_from_hand

### ISSUE THREAD

**Issue by sdevin** [Greg8978/toaster#17]
When you call remove_from_hand in pdg, the object return to the position before it was attached to the joint, it should remains where it is.

**Comment by Greg8978** [comment]
When you use put in hand, it ignores the perception layer to put the object in the hand.
When you remove from hand, it put the object where the robot perceive it.
So for ToasterSimu, I can send a request to ToasterSimu to change the object position.

For other sensors, it should stay at the position untill new perception data...

**Comment by Greg8978** [comment]
Fixed on master for ToasterSimu

**Comment by Greg8978** [comment]
done in this [commit ](https://github.com/Greg8978/toaster/commit/c64709c55a6fcb0ff1b7c9e56b8e820070b6c5a2)
