### ISSUE TITLE
Toaster visualizer seg fault when unknown object

### ISSUE THREAD

**Issue by sdevin** [Greg8978/toaster#47]
All in the title.
Toaster visualizer seg fault when I add a new object on toaster (toaster simu in my tests) and this object isn't in list_obj.xml (instead of putting a blue cube like before)

**Comment by Greg8978** [comment]
After quick look, I don't see anything wrong in the code:

[`marker.type = visualization_msgs::Marker::CUBE; //marker by default`](https://github.com/Greg8978/toaster/blob/master/toaster_visualizer/src/run.cpp#L347)

It will need further investigation to debug...

**Comment by Greg8978** [comment]
I don't have any issue...

Please check that the bug comes from visualization and try to track it down to help debugging :)

Cheers

![screenshot from 2016-09-08 14 43 23](https://cloud.githubusercontent.com/assets/458956/18349723/f7f5046a-75d2-11e6-8ba7-00534e6007a4.png)

**Comment by Greg8978** [comment]
I close this bug for now as no one else experienced it...
