### ISSUE TITLE
rosrun pdg pdg Does not work 

### ISSUE THREAD

**Issue by samialperen** [Greg8978/toaster#59]
SOLVED: If rosrun pdg pdg does not work, or other toaster nodes and you are saying that last time it was working and i did not do anything. Then this error because of export $TOASTERLIB_DIR. Each time you login into new session you need to do this. For permanent solution just add export TOASTERLIB_DIR=your_install_prefix to .bashrc file. Still you have the error then go catkin_ws/build and delete CMakeCache files.
Also a little useful note for the people who just start to work with toaster: While following the document toaster_visualizer.doc. After opening toaster_visualizer node, do not forget to run also pdg since visualizer nodes subscribes pdg. After running pdg you can open rviz.

**Comment by GregoireMilliez** [comment]
Please ensure that you run catkin_make in /home/alperen/catkin_ws/
Once done, check that you have no error and that your pdg executable was generated.

**Comment by samialperen** [comment]
Thank you for your quick response. I edited the question and write the solution. I do not know why but CMakeCache files somehow affects new export commands. Thanks again :+1:

**Comment by Greg8978** [comment]
You are welcome, thank you for the feedback.
I moved your issue into FAQ of the wiki and I will now close this thread as it is solved.
Thanks.
Greg
