### ISSUE TITLE
strange management of memory

### ISSUE THREAD

**Issue by sarthou** [Greg8978/toaster#67]
https://github.com/laas/toaster/blob/22b31fe44f7a3d208855bac8ca5919a44cecab7f/agent_monitor/src/main.cpp#L1047

Why is a new empty robot or a new empty human being created to replace the previous one? The previous one is never deleted and this can be dangerous ...
Is it really necessary?

**Comment by GregoireMilliez** [comment]
Hello :)
If I remember well, the idea was to swap the pointers.
agntCur is used to feel the ringbuffer, and the new pointer is used to get the next incoming agent data.

I may be wrong but I think the circular buffer delete the pointer once it's not used anymore.
I don't remember having memory leaks, but if you are not sure you can check the circular buffer or test agent_monitor with valgrind.

**Comment by sarthou** [comment]
There is no pointer deletion in the boost circular buffer or in your TRBuffer. I'll fix it!
Thank you for your prompt response

**Comment by GregoireMilliez** [comment]
Ok, my bad. I guess I didn't had issue with this because the data is not that big and experiment are usually not that long...
